# -*- coding: utf-8 -*-
"""OT Note Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-brEKhEOlDuVzZd_zd3sBcSYLUdzzYpN
"""

!pip install streamlit

import streamlit as st

st.title("Occupational Therapy Note Generator")

# Define intervention types
interventions = {
    "ADLs": "Patient participated in ADL training with OT providing cues to increase independence and safety, including {details}.",
    "Upper Extremity Exercises": "Patient performed upper extremity therapeutic exercises targeting {details}, OT provided cues for optimal technique",
    "Balance Training": "Balance activities included {details} to improve stability and safety, OT provided cues and assistance.",
    "Functional Mobility": "Patient engaged in functional mobility training including {details}, OT provided cues and assistance for safe technique",
    "Safety Education": "OT reviewed safety precautions including use of device at all times, slow position changes, and wear of non-skid footwear."
}

# --- Input Form ---
with st.form("ot_note_form"):
    intervention_type = st.selectbox("Intervention Type", list(interventions.keys()))
    details = st.text_area(f"Describe the {intervention_type.lower()} intervention")
    assistance_level = st.selectbox("Assistance Level", ["Independent", "CGA", "Min assist", "Mod assist", "Max assist", "Dependent"])
    submit = st.form_submit_button("Generate Note")

# --- Note Generation ---
if submit:
    intervention_text = interventions[intervention_type].format(details=details)

    note = f"""
**O:**
- {intervention_text}
- Assistance level required: {assistance_level}

**A:**
Client demonstrating gains with {intervention_type.lower()}.

**P:**
{plan}
"""
    st.markdown("### Generated OT Note")
    st.code(note, language='markdown')

    st.download_button("Download Note", data=note, file_name=f"{patient_name.replace(' ', '_')}_{note_date}.txt")
